### ISSUE TITLE
Events reference, returns a 404 response

### ISSUE THREAD

**Issue by sauravhiremath** [GDGVIT/projects-ideas#125]
The following link needs to be updated. Returns a **404** response as of now.

#### This line requires a change. [Click here](https://github.com/GDGVIT/projects-ideas/blob/3fad9b304e6afabc9d0df26939e1bc45e990a3dc/_includes/header.html#L31)

**Comment by Geek-ubaid** [comment]
You can check out our new website [here](https://github.com/GDGVIT/project-ideas-v2-frontend)
