### ISSUE TITLE
Error: website unavailable!

### ISSUE THREAD

**Issue by BaseMax** [GDGVIT/projects-ideas#126]
Dear @aalind0,
Hello Aalind Singh,

This website is unavailable and cannot access to it.
http://ideas.dscvit.com/
#### Hmm. We’re having trouble finding that site.
> We can’t connect to the server at ideas.dscvit.com.

#### $ ping ideas.dscvit.com
> ping: ideas.dscvit.com: Name or service not known
https://toolbox.googleapps.com/apps/dig/#A/

#### $ curl http://ideas.dscvit.com/
> curl: (6) Could not resolve host: ideas.dscvit.com

Best,
Max Base

**Comment by L04DB4L4NC3R** [comment]
Hi @BaseMax , the site is now live, as of #127 . Thank you.
