### ISSUE TITLE
 http://ideas.gdgvitvellore.com/ top bar links to a rather dead looking http://projects.gdgvitvellore.com/

### ISSUE THREAD

**Issue by ashwini0529** [GDGVIT/projects-ideas#31]

**Comment by aalind0** [comment]
@ashwini0529  A temporary [landing](http://projects.gdgvitvellore.com/) page is up now, until the projects site is fully designed.

**Comment by Geek-ubaid** [comment]
This repo is no longer maintained, check out the new repo [here](https://github.com/GDGVIT/project-ideas-v2-frontend)
