### ISSUE TITLE
Form not submitting. Getting {status : False} response

### ISSUE THREAD

**Issue by PiyushGoyal443** [GDGVIT/projects-ideas#34]
After filling all the credentials, user is not able to submit the form. Screenshot is attached
![image](https://cloud.githubusercontent.com/assets/10668915/25074100/e001f8b2-2311-11e7-93ff-fbf4b15e379f.png)

**Comment by aalind0** [comment]
@PiyushGoyal443 Issue fixed. Now you can submit your idea.
